### ISSUE TITLE
enhancement: add function awaitSuccessful() 

### ISSUE THREAD

**Issue by SimonHeimberg** [clue/php-block-react#29]
Use case:
I want to use Clue\React\Buzz\Browser to do several requests in parallel and return all successful responses.  (To get the failing responses is a plus, since it allows things like logging.)
I expect it to be called similar as awaitAll() shown in https://github.com/clue/php-buzz-react#blocking . 

Expected return value:
suggestion: 
```php
[
    ['pass' => true, 'value' => Response1],
    ['pass' => false, 'reason' => Failure2],
    ['pass' => true, 'value' => Response3],
    ['pass' => false, 'reason' => Failure4],
]
```

Providing a timeout should work as well. On timeout, the remaining Promises should be reported as failed.

**Comment by SimonHeimberg** [comment]
some details in https://github.com/reactphp/promise/issues/101

**Comment by SimonHeimberg** [comment]
Can now be done with https://github.com/EmchBerger/react-settle-promise:

```php
use CubeTools\React\SettlePromise;
use Clue\React\Block;

$loop = \React\EventLoop\Factory::create();

$states = Block\await(SettlePromise\settleWithTimeout($promiseArray, 4, $loop), $loop);
```

**Comment by clue** [comment]
Thank you for filing this ticket and providing this implementation! :+1: 

I think providing this as a separate package and providing documentation here in the form of this ticket makes perfect sense. If this turns out to be common usage pattern, then I'm not opposed to getting this in here and help promote this approach. For now however, I think having this separate is the way forward.

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:
